#! /bin/sh

setxkbmap it &

bspc monitor -d 1 2 3 4

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle false
bspc config single_monocle true
bspc config gapless_monocle false

bspc config focused_border_color "#81a1c1"
bspc config normal_border_color "#4c566a"

polybar bar &
feh --bg-scale $HOME/Immagini/Sfondo.jpg &
dunst &
picom &
